# Generated by Django 5.1.5 on 2025-02-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_created_project_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create',
            new_name='created',
        ),
    ]
